<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ProductNameColor</name>
   <tag></tag>
   <elementGuidId>a1a424b2-a621-4f61-898d-3cb964d59c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.product-name > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-6']/div/div/form/table/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ecbaa0b-1adc-4521-bd02-5fd31f253425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/product/pink-drop-shoulder-oversized-t-shirt/?attribute_pa_color=pink&amp;attribute_pa_size=37</value>
      <webElementGuid>cd63f2a1-a8ed-457c-a75f-184aa9c730f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pink drop shoulder oversized t shirt - Pink</value>
      <webElementGuid>3a10217d-442b-4317-9bc4-32fff0942591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-6&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[1]/table[@class=&quot;shop_table shop_table_responsive cart&quot;]/tbody[1]/tr[@class=&quot;cart_item&quot;]/td[@class=&quot;product-name&quot;]/a[1]</value>
      <webElementGuid>fa7a9003-c628-4782-b29b-2120820ad1c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-6']/div/div/form/table/tbody/tr/td[2]/a</value>
      <webElementGuid>a0ee3b8d-6602-4d63-909a-091011a00784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'pink drop shoulder oversized t shirt - Pink')]</value>
      <webElementGuid>541ec00a-f393-46bd-8428-9db77550e398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[2]</value>
      <webElementGuid>dd650f77-797f-4e57-93e6-e9918af5e064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::a[2]</value>
      <webElementGuid>238c2dee-7a42-4420-af82-5ee5f5367a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size:'])[1]/preceding::a[1]</value>
      <webElementGuid>6dd5d2e7-6e9a-4840-84ae-fd9264834d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[4]/preceding::a[1]</value>
      <webElementGuid>d2717cd1-efc9-474f-9afc-472558998d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pink drop shoulder oversized t shirt - Pink']/parent::*</value>
      <webElementGuid>56096ed0-6583-47b0-9b00-d2ef1fdcd1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://shop.demoqa.com/product/pink-drop-shoulder-oversized-t-shirt/?attribute_pa_color=pink&amp;attribute_pa_size=37')])[2]</value>
      <webElementGuid>bb6ca83f-19bc-4ed4-bcd4-52830826a5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>307a313f-1a1b-4834-bb4d-38ca3d858e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://shop.demoqa.com/product/pink-drop-shoulder-oversized-t-shirt/?attribute_pa_color=pink&amp;attribute_pa_size=37' and (text() = 'pink drop shoulder oversized t shirt - Pink' or . = 'pink drop shoulder oversized t shirt - Pink')]</value>
      <webElementGuid>d85b2c40-38f3-474c-819a-d9f8ad410990</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
