<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agrement</name>
   <tag></tag>
   <elementGuidId>f5b02ab5-ed6a-49e6-ae1d-4060ee8d89fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='terms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9f84924-6583-4b3c-929e-5e3b02127152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a1b0b6c9-52ec-4552-9150-4fbeb6ffa856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox input-checkbox</value>
      <webElementGuid>54d1ac56-8382-453c-8c56-88faedbfea4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>1ec9b040-fcb1-4bb1-80f3-350e669898ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>70c1916f-9acc-4561-b51c-eee2be4500aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms&quot;)</value>
      <webElementGuid>53e0d702-286e-431e-b11b-6df49e37e679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='terms']</value>
      <webElementGuid>3e671644-9dbb-46ad-875b-e74724705b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/div/div/p/label/input</value>
      <webElementGuid>611a9a1a-3504-4334-ab35-a41860123f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/p/label/input</value>
      <webElementGuid>923c1fcc-8456-4d7c-b419-9954955ae533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'terms' and @id = 'terms']</value>
      <webElementGuid>772fcbb0-de54-401a-ac68-1836b9ab0c8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
