<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone</name>
   <tag></tag>
   <elementGuidId>7676e7dd-8b85-42df-b108-5e621a1b66a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dda98c18-36ef-4e57-9e39-2143a2cf21d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>eff85af6-e8fb-4dc3-a026-3cc6db9ce7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>b1a10444-3833-405c-9846-03604f1f5d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_phone</value>
      <webElementGuid>4bc3e492-8a23-4218-b739-581eadbf1dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_phone</value>
      <webElementGuid>002cd82b-01d1-4daf-86e5-7c544c094497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2c0d28ea-3313-43e6-a4ba-c85cef48cd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_phone&quot;)</value>
      <webElementGuid>68604db9-11bf-4c4b-abab-b9b965165f80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_phone']</value>
      <webElementGuid>7bcf0b7c-23a6-4a7a-964d-107ce5858cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_phone_field']/span/input</value>
      <webElementGuid>7de7ed72-ff9e-4d6a-ab67-1890fb8d2965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/span/input</value>
      <webElementGuid>45f5c16a-9805-4c4f-8f4e-5c5906d8322c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'billing_phone' and @id = 'billing_phone']</value>
      <webElementGuid>08ec030b-54dc-4c83-8462-1ba6c7580b4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
