<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CreateAccount</name>
   <tag></tag>
   <elementGuidId>70389298-996a-490b-926a-218806e39e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createaccount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='createaccount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7cd03083-ef79-414e-8fe6-88308cf71acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox input-checkbox</value>
      <webElementGuid>f79c1c84-83e7-44e6-978f-64d4a5e18e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createaccount</value>
      <webElementGuid>8539b690-ca74-4bfd-bfca-ce4df4d098b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d67e4fe3-f537-4a65-b66e-22e0a511ab0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>createaccount</value>
      <webElementGuid>d1573384-643f-4cbf-ad91-f775739c082d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e0fbc3a8-3619-4977-a8fc-8e5b2a7f69f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createaccount&quot;)</value>
      <webElementGuid>bd00f73b-9a06-4335-b39f-abe44178583b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='createaccount']</value>
      <webElementGuid>b7b50835-4a2d-4ce6-9738-1fdaf13bb173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_details']/div[2]/p/label/input</value>
      <webElementGuid>b637a5d7-30a4-471b-8ba5-97513f5b144b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/label/input</value>
      <webElementGuid>6ea641ae-1555-40b2-ad6f-5ee0760b7e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'createaccount' and @type = 'checkbox' and @name = 'createaccount']</value>
      <webElementGuid>76a1b67c-a2a0-4001-bcdf-6348dbcfc4d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
