<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address1</name>
   <tag></tag>
   <elementGuidId>f88e8374-8ac3-4479-acfa-5be0e79219ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_address_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_address_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d8caeef-9e7a-4848-a5ea-2981be21b3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f56ab461-e821-41f3-9498-5bca0c997abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>a8b28955-3123-431d-80a5-42123ee77796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_address_1</value>
      <webElementGuid>0f492208-59da-4bb8-9e13-c09feaad46f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_address_1</value>
      <webElementGuid>4c4acc42-6758-46c8-bdfa-ea203ac6e194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>House number and street name</value>
      <webElementGuid>d8948e92-ba44-4c9a-baeb-d02ab4a7c97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-line1</value>
      <webElementGuid>3be4a256-cfd2-45cd-9a3c-099ad6bfb763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>House number and street name</value>
      <webElementGuid>2fffb346-0337-43c8-8af1-959b190a0272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_address_1&quot;)</value>
      <webElementGuid>abcb9fb7-0828-470e-85a0-de883a4cd6ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_address_1']</value>
      <webElementGuid>d56336d4-d9c9-44cb-b897-9e834c1a18aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_address_1_field']/span/input</value>
      <webElementGuid>3641e1c0-42b7-453d-bb58-5aab71015f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/span/input</value>
      <webElementGuid>f8ad68c5-0c08-4bef-8740-dcab21504276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_address_1' and @id = 'billing_address_1' and @placeholder = 'House number and street name']</value>
      <webElementGuid>129505ea-a6f2-44f9-9131-4e84e106de58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
